/*
 * Cloud Memorystore for Memcached API
 * Google Cloud Memorystore for Memcached API is used for creating and managing Memcached instances in GCP.
 *
 * The version of the OpenAPI document: v1beta2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApplyParametersRequest
 */
public class ApplyParametersRequestTest {
    private final ApplyParametersRequest model = new ApplyParametersRequest();

    /**
     * Model tests for ApplyParametersRequest
     */
    @Test
    public void testApplyParametersRequest() {
        // TODO: test ApplyParametersRequest
    }

    /**
     * Test the property 'applyAll'
     */
    @Test
    public void applyAllTest() {
        // TODO: test applyAll
    }

    /**
     * Test the property 'nodeIds'
     */
    @Test
    public void nodeIdsTest() {
        // TODO: test nodeIds
    }

}
