/*
 * Cloud Memorystore for Memcached API
 * Google Cloud Memorystore for Memcached API is used for creating and managing Memcached instances in GCP.
 *
 * The version of the OpenAPI document: v1beta2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadata;
import org.openapitools.client.model.GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibility;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GoogleCloudSaasacceleratorManagementProvidersV1SloMetadata
 */
public class GoogleCloudSaasacceleratorManagementProvidersV1SloMetadataTest {
    private final GoogleCloudSaasacceleratorManagementProvidersV1SloMetadata model = new GoogleCloudSaasacceleratorManagementProvidersV1SloMetadata();

    /**
     * Model tests for GoogleCloudSaasacceleratorManagementProvidersV1SloMetadata
     */
    @Test
    public void testGoogleCloudSaasacceleratorManagementProvidersV1SloMetadata() {
        // TODO: test GoogleCloudSaasacceleratorManagementProvidersV1SloMetadata
    }

    /**
     * Test the property 'nodes'
     */
    @Test
    public void nodesTest() {
        // TODO: test nodes
    }

    /**
     * Test the property 'perSliEligibility'
     */
    @Test
    public void perSliEligibilityTest() {
        // TODO: test perSliEligibility
    }

    /**
     * Test the property 'tier'
     */
    @Test
    public void tierTest() {
        // TODO: test tier
    }

}
