/*
 * Cloud Memorystore for Memcached API
 * Google Cloud Memorystore for Memcached API is used for creating and managing Memcached instances in GCP.
 *
 * The version of the OpenAPI document: v1beta2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource
 */
public class GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResourceTest {
    private final GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource model = new GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource();

    /**
     * Model tests for GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource
     */
    @Test
    public void testGoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource() {
        // TODO: test GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource
    }

    /**
     * Test the property 'resourceType'
     */
    @Test
    public void resourceTypeTest() {
        // TODO: test resourceType
    }

    /**
     * Test the property 'resourceUrl'
     */
    @Test
    public void resourceUrlTest() {
        // TODO: test resourceUrl
    }

}
