/*
 * Cloud Memorystore for Memcached API
 * Google Cloud Memorystore for Memcached API is used for creating and managing Memcached instances in GCP.
 *
 * The version of the OpenAPI document: v1beta2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.client.model.GoogleCloudSaasacceleratorManagementProvidersV1SloEligibility;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibility
 */
public class GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibilityTest {
    private final GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibility model = new GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibility();

    /**
     * Model tests for GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibility
     */
    @Test
    public void testGoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibility() {
        // TODO: test GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibility
    }

    /**
     * Test the property 'eligibilities'
     */
    @Test
    public void eligibilitiesTest() {
        // TODO: test eligibilities
    }

}
