/*
 * Cloud Memorystore for Memcached API
 * Google Cloud Memorystore for Memcached API is used for creating and managing Memcached instances in GCP.
 *
 * The version of the OpenAPI document: v1beta2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibility;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadata
 */
public class GoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadataTest {
    private final GoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadata model = new GoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadata();

    /**
     * Model tests for GoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadata
     */
    @Test
    public void testGoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadata() {
        // TODO: test GoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadata
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'nodeId'
     */
    @Test
    public void nodeIdTest() {
        // TODO: test nodeId
    }

    /**
     * Test the property 'perSliEligibility'
     */
    @Test
    public void perSliEligibilityTest() {
        // TODO: test perSliEligibility
    }

}
