/*
 * Cloud Memorystore for Memcached API
 * Google Cloud Memorystore for Memcached API is used for creating and managing Memcached instances in GCP.
 *
 * The version of the OpenAPI document: v1beta2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.client.model.MaintenancePolicy;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettings
 */
public class GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettingsTest {
    private final GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettings model = new GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettings();

    /**
     * Model tests for GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettings
     */
    @Test
    public void testGoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettings() {
        // TODO: test GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettings
    }

    /**
     * Test the property 'exclude'
     */
    @Test
    public void excludeTest() {
        // TODO: test exclude
    }

    /**
     * Test the property 'isRollback'
     */
    @Test
    public void isRollbackTest() {
        // TODO: test isRollback
    }

    /**
     * Test the property 'maintenancePolicies'
     */
    @Test
    public void maintenancePoliciesTest() {
        // TODO: test maintenancePolicies
    }

}
