/*
 * Cloud Memorystore for Memcached API
 * Google Cloud Memorystore for Memcached API is used for creating and managing Memcached instances in GCP.
 *
 * The version of the OpenAPI document: v1beta2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.WeeklyMaintenanceWindow;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GoogleCloudMemcacheV1beta2MaintenancePolicy
 */
public class GoogleCloudMemcacheV1beta2MaintenancePolicyTest {
    private final GoogleCloudMemcacheV1beta2MaintenancePolicy model = new GoogleCloudMemcacheV1beta2MaintenancePolicy();

    /**
     * Model tests for GoogleCloudMemcacheV1beta2MaintenancePolicy
     */
    @Test
    public void testGoogleCloudMemcacheV1beta2MaintenancePolicy() {
        // TODO: test GoogleCloudMemcacheV1beta2MaintenancePolicy
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'updateTime'
     */
    @Test
    public void updateTimeTest() {
        // TODO: test updateTime
    }

    /**
     * Test the property 'weeklyMaintenanceWindow'
     */
    @Test
    public void weeklyMaintenanceWindowTest() {
        // TODO: test weeklyMaintenanceWindow
    }

}
