/*
 * Cloud Memorystore for Memcached API
 * Google Cloud Memorystore for Memcached API is used for creating and managing Memcached instances in GCP.
 *
 * The version of the OpenAPI document: v1beta2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GoogleCloudSaasacceleratorManagementProvidersV1SloEligibility
 */
public class GoogleCloudSaasacceleratorManagementProvidersV1SloEligibilityTest {
    private final GoogleCloudSaasacceleratorManagementProvidersV1SloEligibility model = new GoogleCloudSaasacceleratorManagementProvidersV1SloEligibility();

    /**
     * Model tests for GoogleCloudSaasacceleratorManagementProvidersV1SloEligibility
     */
    @Test
    public void testGoogleCloudSaasacceleratorManagementProvidersV1SloEligibility() {
        // TODO: test GoogleCloudSaasacceleratorManagementProvidersV1SloEligibility
    }

    /**
     * Test the property 'eligible'
     */
    @Test
    public void eligibleTest() {
        // TODO: test eligible
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

}
