/*
 * Cloud Memorystore for Memcached API
 * Google Cloud Memorystore for Memcached API is used for creating and managing Memcached instances in GCP.
 *
 * The version of the OpenAPI document: v1beta2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GoogleCloudMemcacheV1beta2OperationMetadata
 */
public class GoogleCloudMemcacheV1beta2OperationMetadataTest {
    private final GoogleCloudMemcacheV1beta2OperationMetadata model = new GoogleCloudMemcacheV1beta2OperationMetadata();

    /**
     * Model tests for GoogleCloudMemcacheV1beta2OperationMetadata
     */
    @Test
    public void testGoogleCloudMemcacheV1beta2OperationMetadata() {
        // TODO: test GoogleCloudMemcacheV1beta2OperationMetadata
    }

    /**
     * Test the property 'apiVersion'
     */
    @Test
    public void apiVersionTest() {
        // TODO: test apiVersion
    }

    /**
     * Test the property 'cancelRequested'
     */
    @Test
    public void cancelRequestedTest() {
        // TODO: test cancelRequested
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    public void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'statusDetail'
     */
    @Test
    public void statusDetailTest() {
        // TODO: test statusDetail
    }

    /**
     * Test the property 'target'
     */
    @Test
    public void targetTest() {
        // TODO: test target
    }

    /**
     * Test the property 'verb'
     */
    @Test
    public void verbTest() {
        // TODO: test verb
    }

}
