/*
 * Cloud Memorystore for Memcached API
 * Google Cloud Memorystore for Memcached API is used for creating and managing Memcached instances in GCP.
 *
 * The version of the OpenAPI document: v1beta2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.GoogleCloudMemcacheV1beta2MaintenancePolicy;
import org.openapitools.client.model.InstanceMessage;
import org.openapitools.client.model.MaintenanceSchedule;
import org.openapitools.client.model.MemcacheParameters;
import org.openapitools.client.model.Node;
import org.openapitools.client.model.NodeConfig;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Instance
 */
public class InstanceTest {
    private final Instance model = new Instance();

    /**
     * Model tests for Instance
     */
    @Test
    public void testInstance() {
        // TODO: test Instance
    }

    /**
     * Test the property 'authorizedNetwork'
     */
    @Test
    public void authorizedNetworkTest() {
        // TODO: test authorizedNetwork
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

    /**
     * Test the property 'discoveryEndpoint'
     */
    @Test
    public void discoveryEndpointTest() {
        // TODO: test discoveryEndpoint
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'instanceMessages'
     */
    @Test
    public void instanceMessagesTest() {
        // TODO: test instanceMessages
    }

    /**
     * Test the property 'labels'
     */
    @Test
    public void labelsTest() {
        // TODO: test labels
    }

    /**
     * Test the property 'maintenancePolicy'
     */
    @Test
    public void maintenancePolicyTest() {
        // TODO: test maintenancePolicy
    }

    /**
     * Test the property 'maintenanceSchedule'
     */
    @Test
    public void maintenanceScheduleTest() {
        // TODO: test maintenanceSchedule
    }

    /**
     * Test the property 'memcacheFullVersion'
     */
    @Test
    public void memcacheFullVersionTest() {
        // TODO: test memcacheFullVersion
    }

    /**
     * Test the property 'memcacheNodes'
     */
    @Test
    public void memcacheNodesTest() {
        // TODO: test memcacheNodes
    }

    /**
     * Test the property 'memcacheVersion'
     */
    @Test
    public void memcacheVersionTest() {
        // TODO: test memcacheVersion
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'nodeConfig'
     */
    @Test
    public void nodeConfigTest() {
        // TODO: test nodeConfig
    }

    /**
     * Test the property 'nodeCount'
     */
    @Test
    public void nodeCountTest() {
        // TODO: test nodeCount
    }

    /**
     * Test the property 'parameters'
     */
    @Test
    public void parametersTest() {
        // TODO: test parameters
    }

    /**
     * Test the property 'reservedIpRangeId'
     */
    @Test
    public void reservedIpRangeIdTest() {
        // TODO: test reservedIpRangeId
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'updateAvailable'
     */
    @Test
    public void updateAvailableTest() {
        // TODO: test updateAvailable
    }

    /**
     * Test the property 'updateTime'
     */
    @Test
    public void updateTimeTest() {
        // TODO: test updateTime
    }

    /**
     * Test the property 'zones'
     */
    @Test
    public void zonesTest() {
        // TODO: test zones
    }

}
