/*
 * Cloud Memorystore for Memcached API
 * Google Cloud Memorystore for Memcached API is used for creating and managing Memcached instances in GCP.
 *
 * The version of the OpenAPI document: v1beta2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LocationMetadata
 */
public class LocationMetadataTest {
    private final LocationMetadata model = new LocationMetadata();

    /**
     * Model tests for LocationMetadata
     */
    @Test
    public void testLocationMetadata() {
        // TODO: test LocationMetadata
    }

    /**
     * Test the property 'availableZones'
     */
    @Test
    public void availableZonesTest() {
        // TODO: test availableZones
    }

}
