/*
 * Cloud Memorystore for Memcached API
 * Google Cloud Memorystore for Memcached API is used for creating and managing Memcached instances in GCP.
 *
 * The version of the OpenAPI document: v1beta2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.DailyCycle;
import org.openapitools.client.model.WeeklyCycle;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MaintenanceWindow
 */
public class MaintenanceWindowTest {
    private final MaintenanceWindow model = new MaintenanceWindow();

    /**
     * Model tests for MaintenanceWindow
     */
    @Test
    public void testMaintenanceWindow() {
        // TODO: test MaintenanceWindow
    }

    /**
     * Test the property 'dailyCycle'
     */
    @Test
    public void dailyCycleTest() {
        // TODO: test dailyCycle
    }

    /**
     * Test the property 'weeklyCycle'
     */
    @Test
    public void weeklyCycleTest() {
        // TODO: test weeklyCycle
    }

}
