/*
 * Cloud Memorystore for Memcached API
 * Google Cloud Memorystore for Memcached API is used for creating and managing Memcached instances in GCP.
 *
 * The version of the OpenAPI document: v1beta2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NodeConfig
 */
public class NodeConfigTest {
    private final NodeConfig model = new NodeConfig();

    /**
     * Model tests for NodeConfig
     */
    @Test
    public void testNodeConfig() {
        // TODO: test NodeConfig
    }

    /**
     * Test the property 'cpuCount'
     */
    @Test
    public void cpuCountTest() {
        // TODO: test cpuCount
    }

    /**
     * Test the property 'memorySizeMb'
     */
    @Test
    public void memorySizeMbTest() {
        // TODO: test memorySizeMb
    }

}
