/*
 * Cloud Memorystore for Memcached API
 * Google Cloud Memorystore for Memcached API is used for creating and managing Memcached instances in GCP.
 *
 * The version of the OpenAPI document: v1beta2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RescheduleMaintenanceRequest
 */
public class RescheduleMaintenanceRequestTest {
    private final RescheduleMaintenanceRequest model = new RescheduleMaintenanceRequest();

    /**
     * Model tests for RescheduleMaintenanceRequest
     */
    @Test
    public void testRescheduleMaintenanceRequest() {
        // TODO: test RescheduleMaintenanceRequest
    }

    /**
     * Test the property 'rescheduleType'
     */
    @Test
    public void rescheduleTypeTest() {
        // TODO: test rescheduleType
    }

    /**
     * Test the property 'scheduleTime'
     */
    @Test
    public void scheduleTimeTest() {
        // TODO: test scheduleTime
    }

}
