/*
 * Cloud Memorystore for Memcached API
 * Google Cloud Memorystore for Memcached API is used for creating and managing Memcached instances in GCP.
 *
 * The version of the OpenAPI document: v1beta2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.DenyMaintenancePeriod;
import org.openapitools.client.model.MaintenanceWindow;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdatePolicy
 */
public class UpdatePolicyTest {
    private final UpdatePolicy model = new UpdatePolicy();

    /**
     * Model tests for UpdatePolicy
     */
    @Test
    public void testUpdatePolicy() {
        // TODO: test UpdatePolicy
    }

    /**
     * Test the property 'channel'
     */
    @Test
    public void channelTest() {
        // TODO: test channel
    }

    /**
     * Test the property 'denyMaintenancePeriods'
     */
    @Test
    public void denyMaintenancePeriodsTest() {
        // TODO: test denyMaintenancePeriods
    }

    /**
     * Test the property 'window'
     */
    @Test
    public void windowTest() {
        // TODO: test window
    }

}
