/*
 * Cloud Memorystore for Memcached API
 * Google Cloud Memorystore for Memcached API is used for creating and managing Memcached instances in GCP.
 *
 * The version of the OpenAPI document: v1beta2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Request for UpgradeInstance.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T15:33:03.624322+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class GoogleCloudMemcacheV1beta2UpgradeInstanceRequest {
  /**
   * Required. Specifies the target version of memcached engine to upgrade to.
   */
  @JsonAdapter(MemcacheVersionEnum.Adapter.class)
  public enum MemcacheVersionEnum {
    MEMCACHE_VERSION_UNSPECIFIED("MEMCACHE_VERSION_UNSPECIFIED"),
    
    MEMCACHE_1_5("MEMCACHE_1_5"),
    
    MEMCACHE_1_6_15("MEMCACHE_1_6_15");

    private String value;

    MemcacheVersionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static MemcacheVersionEnum fromValue(String value) {
      for (MemcacheVersionEnum b : MemcacheVersionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<MemcacheVersionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final MemcacheVersionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public MemcacheVersionEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return MemcacheVersionEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      MemcacheVersionEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_MEMCACHE_VERSION = "memcacheVersion";
  @SerializedName(SERIALIZED_NAME_MEMCACHE_VERSION)
  @javax.annotation.Nullable
  private MemcacheVersionEnum memcacheVersion;

  public GoogleCloudMemcacheV1beta2UpgradeInstanceRequest() {
  }

  public GoogleCloudMemcacheV1beta2UpgradeInstanceRequest memcacheVersion(@javax.annotation.Nullable MemcacheVersionEnum memcacheVersion) {
    this.memcacheVersion = memcacheVersion;
    return this;
  }

  /**
   * Required. Specifies the target version of memcached engine to upgrade to.
   * @return memcacheVersion
   */
  @javax.annotation.Nullable
  public MemcacheVersionEnum getMemcacheVersion() {
    return memcacheVersion;
  }

  public void setMemcacheVersion(@javax.annotation.Nullable MemcacheVersionEnum memcacheVersion) {
    this.memcacheVersion = memcacheVersion;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GoogleCloudMemcacheV1beta2UpgradeInstanceRequest googleCloudMemcacheV1beta2UpgradeInstanceRequest = (GoogleCloudMemcacheV1beta2UpgradeInstanceRequest) o;
    return Objects.equals(this.memcacheVersion, googleCloudMemcacheV1beta2UpgradeInstanceRequest.memcacheVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(memcacheVersion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GoogleCloudMemcacheV1beta2UpgradeInstanceRequest {\n");
    sb.append("    memcacheVersion: ").append(toIndentedString(memcacheVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("memcacheVersion"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GoogleCloudMemcacheV1beta2UpgradeInstanceRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GoogleCloudMemcacheV1beta2UpgradeInstanceRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GoogleCloudMemcacheV1beta2UpgradeInstanceRequest is not found in the empty JSON string", GoogleCloudMemcacheV1beta2UpgradeInstanceRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GoogleCloudMemcacheV1beta2UpgradeInstanceRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GoogleCloudMemcacheV1beta2UpgradeInstanceRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("memcacheVersion") != null && !jsonObj.get("memcacheVersion").isJsonNull()) && !jsonObj.get("memcacheVersion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `memcacheVersion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("memcacheVersion").toString()));
      }
      // validate the optional field `memcacheVersion`
      if (jsonObj.get("memcacheVersion") != null && !jsonObj.get("memcacheVersion").isJsonNull()) {
        MemcacheVersionEnum.validateJsonElement(jsonObj.get("memcacheVersion"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GoogleCloudMemcacheV1beta2UpgradeInstanceRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GoogleCloudMemcacheV1beta2UpgradeInstanceRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GoogleCloudMemcacheV1beta2UpgradeInstanceRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GoogleCloudMemcacheV1beta2UpgradeInstanceRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<GoogleCloudMemcacheV1beta2UpgradeInstanceRequest>() {
           @Override
           public void write(JsonWriter out, GoogleCloudMemcacheV1beta2UpgradeInstanceRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GoogleCloudMemcacheV1beta2UpgradeInstanceRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GoogleCloudMemcacheV1beta2UpgradeInstanceRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GoogleCloudMemcacheV1beta2UpgradeInstanceRequest
   * @throws IOException if the JSON string is invalid with respect to GoogleCloudMemcacheV1beta2UpgradeInstanceRequest
   */
  public static GoogleCloudMemcacheV1beta2UpgradeInstanceRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GoogleCloudMemcacheV1beta2UpgradeInstanceRequest.class);
  }

  /**
   * Convert an instance of GoogleCloudMemcacheV1beta2UpgradeInstanceRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

