/*
 * Cloud Memorystore for Memcached API
 * Google Cloud Memorystore for Memcached API is used for creating and managing Memcached instances in GCP.
 *
 * The version of the OpenAPI document: v1beta2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Describes provisioned dataplane resources.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T15:33:03.624322+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource {
  public static final String SERIALIZED_NAME_RESOURCE_TYPE = "resourceType";
  @SerializedName(SERIALIZED_NAME_RESOURCE_TYPE)
  @javax.annotation.Nullable
  private String resourceType;

  public static final String SERIALIZED_NAME_RESOURCE_URL = "resourceUrl";
  @SerializedName(SERIALIZED_NAME_RESOURCE_URL)
  @javax.annotation.Nullable
  private String resourceUrl;

  public GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource() {
  }

  public GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource resourceType(@javax.annotation.Nullable String resourceType) {
    this.resourceType = resourceType;
    return this;
  }

  /**
   * Type of the resource. This can be either a GCP resource or a custom one (e.g. another cloud provider&#39;s VM). For GCP compute resources use singular form of the names listed in GCP compute API documentation (https://cloud.google.com/compute/docs/reference/rest/v1/), prefixed with &#39;compute-&#39;, for example: &#39;compute-instance&#39;, &#39;compute-disk&#39;, &#39;compute-autoscaler&#39;.
   * @return resourceType
   */
  @javax.annotation.Nullable
  public String getResourceType() {
    return resourceType;
  }

  public void setResourceType(@javax.annotation.Nullable String resourceType) {
    this.resourceType = resourceType;
  }


  public GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource resourceUrl(@javax.annotation.Nullable String resourceUrl) {
    this.resourceUrl = resourceUrl;
    return this;
  }

  /**
   * URL identifying the resource, e.g. \&quot;https://www.googleapis.com/compute/v1/projects/...)\&quot;.
   * @return resourceUrl
   */
  @javax.annotation.Nullable
  public String getResourceUrl() {
    return resourceUrl;
  }

  public void setResourceUrl(@javax.annotation.Nullable String resourceUrl) {
    this.resourceUrl = resourceUrl;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource googleCloudSaasacceleratorManagementProvidersV1ProvisionedResource = (GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource) o;
    return Objects.equals(this.resourceType, googleCloudSaasacceleratorManagementProvidersV1ProvisionedResource.resourceType) &&
        Objects.equals(this.resourceUrl, googleCloudSaasacceleratorManagementProvidersV1ProvisionedResource.resourceUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resourceType, resourceUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource {\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    resourceUrl: ").append(toIndentedString(resourceUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("resourceType", "resourceUrl"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource is not found in the empty JSON string", GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("resourceType") != null && !jsonObj.get("resourceType").isJsonNull()) && !jsonObj.get("resourceType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `resourceType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("resourceType").toString()));
      }
      if ((jsonObj.get("resourceUrl") != null && !jsonObj.get("resourceUrl").isJsonNull()) && !jsonObj.get("resourceUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `resourceUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("resourceUrl").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource.class));

       return (TypeAdapter<T>) new TypeAdapter<GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource>() {
           @Override
           public void write(JsonWriter out, GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource
   * @throws IOException if the JSON string is invalid with respect to GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource
   */
  public static GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource.class);
  }

  /**
   * Convert an instance of GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

