/*
 * Cloud Memorystore for Memcached API
 * Google Cloud Memorystore for Memcached API is used for creating and managing Memcached instances in GCP.
 *
 * The version of the OpenAPI document: v1beta2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.DailyCycle;
import org.openapitools.client.model.WeeklyCycle;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * MaintenanceWindow definition.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T15:33:03.624322+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class MaintenanceWindow {
  public static final String SERIALIZED_NAME_DAILY_CYCLE = "dailyCycle";
  @SerializedName(SERIALIZED_NAME_DAILY_CYCLE)
  @javax.annotation.Nullable
  private DailyCycle dailyCycle;

  public static final String SERIALIZED_NAME_WEEKLY_CYCLE = "weeklyCycle";
  @SerializedName(SERIALIZED_NAME_WEEKLY_CYCLE)
  @javax.annotation.Nullable
  private WeeklyCycle weeklyCycle;

  public MaintenanceWindow() {
  }

  public MaintenanceWindow dailyCycle(@javax.annotation.Nullable DailyCycle dailyCycle) {
    this.dailyCycle = dailyCycle;
    return this;
  }

  /**
   * Get dailyCycle
   * @return dailyCycle
   */
  @javax.annotation.Nullable
  public DailyCycle getDailyCycle() {
    return dailyCycle;
  }

  public void setDailyCycle(@javax.annotation.Nullable DailyCycle dailyCycle) {
    this.dailyCycle = dailyCycle;
  }


  public MaintenanceWindow weeklyCycle(@javax.annotation.Nullable WeeklyCycle weeklyCycle) {
    this.weeklyCycle = weeklyCycle;
    return this;
  }

  /**
   * Get weeklyCycle
   * @return weeklyCycle
   */
  @javax.annotation.Nullable
  public WeeklyCycle getWeeklyCycle() {
    return weeklyCycle;
  }

  public void setWeeklyCycle(@javax.annotation.Nullable WeeklyCycle weeklyCycle) {
    this.weeklyCycle = weeklyCycle;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MaintenanceWindow maintenanceWindow = (MaintenanceWindow) o;
    return Objects.equals(this.dailyCycle, maintenanceWindow.dailyCycle) &&
        Objects.equals(this.weeklyCycle, maintenanceWindow.weeklyCycle);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dailyCycle, weeklyCycle);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MaintenanceWindow {\n");
    sb.append("    dailyCycle: ").append(toIndentedString(dailyCycle)).append("\n");
    sb.append("    weeklyCycle: ").append(toIndentedString(weeklyCycle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("dailyCycle", "weeklyCycle"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MaintenanceWindow
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MaintenanceWindow.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MaintenanceWindow is not found in the empty JSON string", MaintenanceWindow.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MaintenanceWindow.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MaintenanceWindow` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `dailyCycle`
      if (jsonObj.get("dailyCycle") != null && !jsonObj.get("dailyCycle").isJsonNull()) {
        DailyCycle.validateJsonElement(jsonObj.get("dailyCycle"));
      }
      // validate the optional field `weeklyCycle`
      if (jsonObj.get("weeklyCycle") != null && !jsonObj.get("weeklyCycle").isJsonNull()) {
        WeeklyCycle.validateJsonElement(jsonObj.get("weeklyCycle"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MaintenanceWindow.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MaintenanceWindow' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MaintenanceWindow> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MaintenanceWindow.class));

       return (TypeAdapter<T>) new TypeAdapter<MaintenanceWindow>() {
           @Override
           public void write(JsonWriter out, MaintenanceWindow value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MaintenanceWindow read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MaintenanceWindow given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MaintenanceWindow
   * @throws IOException if the JSON string is invalid with respect to MaintenanceWindow
   */
  public static MaintenanceWindow fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MaintenanceWindow.class);
  }

  /**
   * Convert an instance of MaintenanceWindow to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

