/*
 * Cloud Memorystore for Memcached API
 * Google Cloud Memorystore for Memcached API is used for creating and managing Memcached instances in GCP.
 *
 * The version of the OpenAPI document: v1beta2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Upcoming maintenance schedule.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T15:33:03.624322+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class MaintenanceSchedule {
  public static final String SERIALIZED_NAME_END_TIME = "endTime";
  @SerializedName(SERIALIZED_NAME_END_TIME)
  @javax.annotation.Nullable
  private String endTime;

  public static final String SERIALIZED_NAME_SCHEDULE_DEADLINE_TIME = "scheduleDeadlineTime";
  @SerializedName(SERIALIZED_NAME_SCHEDULE_DEADLINE_TIME)
  @javax.annotation.Nullable
  private String scheduleDeadlineTime;

  public static final String SERIALIZED_NAME_START_TIME = "startTime";
  @SerializedName(SERIALIZED_NAME_START_TIME)
  @javax.annotation.Nullable
  private String startTime;

  public MaintenanceSchedule() {
  }

  public MaintenanceSchedule(
     String endTime, 
     String scheduleDeadlineTime, 
     String startTime
  ) {
    this();
    this.endTime = endTime;
    this.scheduleDeadlineTime = scheduleDeadlineTime;
    this.startTime = startTime;
  }

  /**
   * Output only. The end time of any upcoming scheduled maintenance for this instance.
   * @return endTime
   */
  @javax.annotation.Nullable
  public String getEndTime() {
    return endTime;
  }



  /**
   * Output only. The deadline that the maintenance schedule start time can not go beyond, including reschedule.
   * @return scheduleDeadlineTime
   */
  @javax.annotation.Nullable
  public String getScheduleDeadlineTime() {
    return scheduleDeadlineTime;
  }



  /**
   * Output only. The start time of any upcoming scheduled maintenance for this instance.
   * @return startTime
   */
  @javax.annotation.Nullable
  public String getStartTime() {
    return startTime;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MaintenanceSchedule maintenanceSchedule = (MaintenanceSchedule) o;
    return Objects.equals(this.endTime, maintenanceSchedule.endTime) &&
        Objects.equals(this.scheduleDeadlineTime, maintenanceSchedule.scheduleDeadlineTime) &&
        Objects.equals(this.startTime, maintenanceSchedule.startTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endTime, scheduleDeadlineTime, startTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MaintenanceSchedule {\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    scheduleDeadlineTime: ").append(toIndentedString(scheduleDeadlineTime)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("endTime", "scheduleDeadlineTime", "startTime"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MaintenanceSchedule
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MaintenanceSchedule.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MaintenanceSchedule is not found in the empty JSON string", MaintenanceSchedule.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MaintenanceSchedule.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MaintenanceSchedule` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("endTime") != null && !jsonObj.get("endTime").isJsonNull()) && !jsonObj.get("endTime").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `endTime` to be a primitive type in the JSON string but got `%s`", jsonObj.get("endTime").toString()));
      }
      if ((jsonObj.get("scheduleDeadlineTime") != null && !jsonObj.get("scheduleDeadlineTime").isJsonNull()) && !jsonObj.get("scheduleDeadlineTime").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `scheduleDeadlineTime` to be a primitive type in the JSON string but got `%s`", jsonObj.get("scheduleDeadlineTime").toString()));
      }
      if ((jsonObj.get("startTime") != null && !jsonObj.get("startTime").isJsonNull()) && !jsonObj.get("startTime").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `startTime` to be a primitive type in the JSON string but got `%s`", jsonObj.get("startTime").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MaintenanceSchedule.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MaintenanceSchedule' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MaintenanceSchedule> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MaintenanceSchedule.class));

       return (TypeAdapter<T>) new TypeAdapter<MaintenanceSchedule>() {
           @Override
           public void write(JsonWriter out, MaintenanceSchedule value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MaintenanceSchedule read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MaintenanceSchedule given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MaintenanceSchedule
   * @throws IOException if the JSON string is invalid with respect to MaintenanceSchedule
   */
  public static MaintenanceSchedule fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MaintenanceSchedule.class);
  }

  /**
   * Convert an instance of MaintenanceSchedule to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

