/*
 * Cloud Memorystore for Memcached API
 * Google Cloud Memorystore for Memcached API is used for creating and managing Memcached instances in GCP.
 *
 * The version of the OpenAPI document: v1beta2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Configuration for a Memcached Node.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T15:33:03.624322+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class NodeConfig {
  public static final String SERIALIZED_NAME_CPU_COUNT = "cpuCount";
  @SerializedName(SERIALIZED_NAME_CPU_COUNT)
  @javax.annotation.Nullable
  private Integer cpuCount;

  public static final String SERIALIZED_NAME_MEMORY_SIZE_MB = "memorySizeMb";
  @SerializedName(SERIALIZED_NAME_MEMORY_SIZE_MB)
  @javax.annotation.Nullable
  private Integer memorySizeMb;

  public NodeConfig() {
  }

  public NodeConfig cpuCount(@javax.annotation.Nullable Integer cpuCount) {
    this.cpuCount = cpuCount;
    return this;
  }

  /**
   * Required. Number of cpus per Memcached node.
   * @return cpuCount
   */
  @javax.annotation.Nullable
  public Integer getCpuCount() {
    return cpuCount;
  }

  public void setCpuCount(@javax.annotation.Nullable Integer cpuCount) {
    this.cpuCount = cpuCount;
  }


  public NodeConfig memorySizeMb(@javax.annotation.Nullable Integer memorySizeMb) {
    this.memorySizeMb = memorySizeMb;
    return this;
  }

  /**
   * Required. Memory size in MiB for each Memcached node.
   * @return memorySizeMb
   */
  @javax.annotation.Nullable
  public Integer getMemorySizeMb() {
    return memorySizeMb;
  }

  public void setMemorySizeMb(@javax.annotation.Nullable Integer memorySizeMb) {
    this.memorySizeMb = memorySizeMb;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeConfig nodeConfig = (NodeConfig) o;
    return Objects.equals(this.cpuCount, nodeConfig.cpuCount) &&
        Objects.equals(this.memorySizeMb, nodeConfig.memorySizeMb);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cpuCount, memorySizeMb);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeConfig {\n");
    sb.append("    cpuCount: ").append(toIndentedString(cpuCount)).append("\n");
    sb.append("    memorySizeMb: ").append(toIndentedString(memorySizeMb)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("cpuCount", "memorySizeMb"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to NodeConfig
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!NodeConfig.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in NodeConfig is not found in the empty JSON string", NodeConfig.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!NodeConfig.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `NodeConfig` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NodeConfig.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NodeConfig' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NodeConfig> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NodeConfig.class));

       return (TypeAdapter<T>) new TypeAdapter<NodeConfig>() {
           @Override
           public void write(JsonWriter out, NodeConfig value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public NodeConfig read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of NodeConfig given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of NodeConfig
   * @throws IOException if the JSON string is invalid with respect to NodeConfig
   */
  public static NodeConfig fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NodeConfig.class);
  }

  /**
   * Convert an instance of NodeConfig to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

